alias ls='/bin/ls -F --color=auto --show-control-chars'
alias l='/bin/ls -la --time-style=long-iso'
alias la='/bin/ls -a --time-style=long-iso'
alias ll='/bin/ls -l --time-style=long-iso'
alias be='bundle exec'
alias dm='docker-machine'
alias xmlstarlet='xml'
alias zstdmt='zstd -T0'
alias unzstd='zstd -d'
alias zstdcat='zstd -dcf'
